version: "3.5"

services:

  node:
    build: .
    container_name: freela_manager_api
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    links:
      - db

  db:
    image: mysql
    container_name: freela_manager_db
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=freelamanager_db
      - MYSQL_ROOT_PASSWORD=root
